// 국내 주요 기업 데이터셋 — 면접 설정 화면 "지원 회사" 검색창 자동완성용
// { name: 회사명, industry: 업종, mark: 워드마크 텍스트, color: 브랜드 색, bg: 칩 배경, aliases: 검색 별칭 }
// 의존성 없는 순수 데이터 + 검색 헬퍼(searchCompanies)

export const COMPANIES = [
  // ── 전자·IT ──────────────────────────────────────────────
  { name: "삼성전자", industry: "전자·IT", mark: "SAMSUNG", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsung", "삼전"] },
  { name: "SK하이닉스", industry: "전자·IT", mark: "SK hynix", color: "#EA002C", bg: "#FFFFFF", aliases: ["skhynix", "hynix", "하이닉스"] },
  { name: "LG전자", industry: "전자·IT", mark: "LG", color: "#A50034", bg: "#FFFFFF", aliases: ["lg", "lge"] },
  { name: "LG디스플레이", industry: "전자·IT", mark: "LG Display", color: "#A50034", bg: "#FFFFFF", aliases: ["lgd", "lgdisplay"] },
  { name: "삼성디스플레이", industry: "전자·IT", mark: "Samsung Display", color: "#1428A0", bg: "#FFFFFF", aliases: ["sdc", "samsungdisplay"] },
  { name: "삼성전기", industry: "전자·IT", mark: "Samsung Electro-Mechanics", color: "#1428A0", bg: "#FFFFFF", aliases: ["semco"] },
  { name: "LG이노텍", industry: "전자·IT", mark: "LG Innotek", color: "#A50034", bg: "#FFFFFF", aliases: ["innotek", "이노텍"] },
  { name: "LS일렉트릭", industry: "전자·IT", mark: "LS ELECTRIC", color: "#C9252B", bg: "#FFFFFF", aliases: ["lselectric", "ls산전"] },
  { name: "삼성SDS", industry: "전자·IT", mark: "Samsung SDS", color: "#1428A0", bg: "#FFFFFF", aliases: ["sds", "samsungsds"] },
  { name: "LG CNS", industry: "전자·IT", mark: "LG CNS", color: "#A50034", bg: "#FFFFFF", aliases: ["lgcns", "cns"] },
  { name: "포스코DX", industry: "전자·IT", mark: "POSCO DX", color: "#05507D", bg: "#FFFFFF", aliases: ["poscodx", "포스코디엑스"] },
  { name: "현대오토에버", industry: "전자·IT", mark: "HYUNDAI AutoEver", color: "#002C5F", bg: "#FFFFFF", aliases: ["autoever", "오토에버"] },
  { name: "한화시스템", industry: "전자·IT", mark: "Hanwha Systems", color: "#F37321", bg: "#FFFFFF", aliases: ["hanwhasystems"] },
  { name: "DB하이텍", industry: "전자·IT", mark: "DB HiTek", color: "#008C44", bg: "#FFFFFF", aliases: ["dbhitek", "디비하이텍"] },
  { name: "안랩", industry: "전자·IT", mark: "AhnLab", color: "#005BAA", bg: "#FFFFFF", aliases: ["ahnlab", "v3"] },
  { name: "한글과컴퓨터", industry: "전자·IT", mark: "Hancom", color: "#0056A8", bg: "#FFFFFF", aliases: ["hancom", "한컴"] },
  { name: "롯데이노베이트", industry: "전자·IT", mark: "LOTTE INNOVATE", color: "#DA291C", bg: "#FFFFFF", aliases: ["lotteinnovate", "롯데정보통신"] },
  { name: "NHN", industry: "전자·IT", mark: "NHN", color: "#00A24C", bg: "#FFFFFF", aliases: ["nhn", "엔에이치엔"] },

  // ── 플랫폼 ───────────────────────────────────────────────
  { name: "네이버", industry: "플랫폼", mark: "NAVER", color: "#03C75A", bg: "#FFFFFF", aliases: ["naver", "네웹"] },
  { name: "네이버웹툰", industry: "플랫폼", mark: "NAVER WEBTOON", color: "#03C75A", bg: "#FFFFFF", aliases: ["webtoon", "naverwebtoon"] },
  { name: "네이버클라우드", industry: "플랫폼", mark: "NAVER Cloud", color: "#03C75A", bg: "#FFFFFF", aliases: ["ncloud", "navercloud"] },
  { name: "라인플러스", industry: "플랫폼", mark: "LINE", color: "#06C755", bg: "#FFFFFF", aliases: ["line", "라인"] },
  { name: "카카오", industry: "플랫폼", mark: "kakao", color: "#000000", bg: "#FEE500", aliases: ["kakao"] },
  { name: "카카오페이", industry: "플랫폼", mark: "kakaopay", color: "#000000", bg: "#FFEB00", aliases: ["kakaopay", "카페이"] },
  { name: "카카오모빌리티", industry: "플랫폼", mark: "kakao mobility", color: "#000000", bg: "#FEE500", aliases: ["kakaomobility", "카모"] },
  { name: "카카오스타일", industry: "플랫폼", mark: "kakaostyle", color: "#000000", bg: "#FEE500", aliases: ["zigzag", "지그재그"] },
  { name: "쿠팡", industry: "플랫폼", mark: "coupang", color: "#E52528", bg: "#FFFFFF", aliases: ["coupang", "cp"] },
  { name: "우아한형제들", industry: "플랫폼", mark: "배달의민족", color: "#2AC1BC", bg: "#FFFFFF", aliases: ["baemin", "woowa", "배민"] },
  { name: "비바리퍼블리카", industry: "플랫폼", mark: "toss", color: "#0064FF", bg: "#FFFFFF", aliases: ["toss", "토스"] },
  { name: "당근", industry: "플랫폼", mark: "당근", color: "#FF6F0F", bg: "#FFFFFF", aliases: ["daangn", "karrot", "당근마켓"] },
  { name: "야놀자", industry: "플랫폼", mark: "yanolja", color: "#FF3478", bg: "#FFFFFF", aliases: ["yanolja"] },
  { name: "무신사", industry: "플랫폼", mark: "MUSINSA", color: "#000000", bg: "#FFFFFF", aliases: ["musinsa"] },
  { name: "컬리", industry: "플랫폼", mark: "Kurly", color: "#5F0080", bg: "#FFFFFF", aliases: ["kurly", "마켓컬리"] },
  { name: "직방", industry: "플랫폼", mark: "zigbang", color: "#FA6B05", bg: "#FFFFFF", aliases: ["zigbang"] },
  { name: "리디", industry: "플랫폼", mark: "RIDI", color: "#1F8CE6", bg: "#FFFFFF", aliases: ["ridi", "ridibooks", "리디북스"] },
  { name: "센드버드", industry: "플랫폼", mark: "Sendbird", color: "#742DDD", bg: "#FFFFFF", aliases: ["sendbird"] },
  { name: "두나무", industry: "플랫폼", mark: "Dunamu", color: "#093687", bg: "#FFFFFF", aliases: ["dunamu", "upbit", "업비트"] },
  { name: "빗썸", industry: "플랫폼", mark: "bithumb", color: "#F7941D", bg: "#FFFFFF", aliases: ["bithumb"] },
  { name: "버킷플레이스", industry: "플랫폼", mark: "오늘의집", color: "#35C5F0", bg: "#FFFFFF", aliases: ["bucketplace", "ohouse", "오늘의집"] },
  { name: "쏘카", industry: "플랫폼", mark: "SOCAR", color: "#00B8F1", bg: "#FFFFFF", aliases: ["socar"] },
  { name: "티맵모빌리티", industry: "플랫폼", mark: "TMAP", color: "#0064FB", bg: "#FFFFFF", aliases: ["tmap", "티맵"] },
  { name: "마이리얼트립", industry: "플랫폼", mark: "myrealtrip", color: "#1C7EF2", bg: "#FFFFFF", aliases: ["myrealtrip", "mrt"] },
  { name: "원티드랩", industry: "플랫폼", mark: "wanted", color: "#3366FF", bg: "#FFFFFF", aliases: ["wanted", "원티드"] },
  { name: "잡코리아", industry: "플랫폼", mark: "JOBKOREA", color: "#2A5CAA", bg: "#FFFFFF", aliases: ["jobkorea", "알바몬"] },
  { name: "몰로코", industry: "플랫폼", mark: "MOLOCO", color: "#4353FF", bg: "#FFFFFF", aliases: ["moloco"] },
  { name: "채널코퍼레이션", industry: "플랫폼", mark: "Channel Talk", color: "#5E56F0", bg: "#FFFFFF", aliases: ["channeltalk", "채널톡"] },

  // ── 게임 ─────────────────────────────────────────────────
  { name: "크래프톤", industry: "게임", mark: "KRAFTON", color: "#000000", bg: "#FFFFFF", aliases: ["krafton", "pubg", "배그"] },
  { name: "넥슨", industry: "게임", mark: "NEXON", color: "#000000", bg: "#FFFFFF", aliases: ["nexon", "메이플"] },
  { name: "엔씨소프트", industry: "게임", mark: "NCSOFT", color: "#000000", bg: "#FFFFFF", aliases: ["ncsoft", "nc", "엔씨"] },
  { name: "넷마블", industry: "게임", mark: "netmarble", color: "#E60012", bg: "#FFFFFF", aliases: ["netmarble"] },
  { name: "스마일게이트", industry: "게임", mark: "SMILEGATE", color: "#FF9C00", bg: "#FFFFFF", aliases: ["smilegate", "로스트아크"] },
  { name: "카카오게임즈", industry: "게임", mark: "kakao games", color: "#000000", bg: "#FEE500", aliases: ["kakaogames", "카겜"] },
  { name: "펄어비스", industry: "게임", mark: "PEARL ABYSS", color: "#1B1464", bg: "#FFFFFF", aliases: ["pearlabyss", "검은사막"] },
  { name: "컴투스", industry: "게임", mark: "Com2uS", color: "#F26B21", bg: "#FFFFFF", aliases: ["com2us"] },
  { name: "위메이드", industry: "게임", mark: "WEMADE", color: "#000000", bg: "#FFFFFF", aliases: ["wemade"] },
  { name: "네오위즈", industry: "게임", mark: "NEOWIZ", color: "#6C2BD9", bg: "#FFFFFF", aliases: ["neowiz"] },
  { name: "시프트업", industry: "게임", mark: "SHIFT UP", color: "#000000", bg: "#FFFFFF", aliases: ["shiftup", "니케"] },
  { name: "데브시스터즈", industry: "게임", mark: "Devsisters", color: "#FF5A1E", bg: "#FFFFFF", aliases: ["devsisters", "쿠키런"] },

  // ── 금융 ─────────────────────────────────────────────────
  { name: "KB국민은행", industry: "금융", mark: "KB", color: "#FFA800", bg: "#FFFFFF", aliases: ["kb", "kbbank", "국민은행"] },
  { name: "신한은행", industry: "금융", mark: "Shinhan Bank", color: "#0046FF", bg: "#FFFFFF", aliases: ["shinhan", "신한"] },
  { name: "하나은행", industry: "금융", mark: "Hana Bank", color: "#008485", bg: "#FFFFFF", aliases: ["hana", "하나"] },
  { name: "우리은행", industry: "금융", mark: "Woori Bank", color: "#0067AC", bg: "#FFFFFF", aliases: ["woori", "우리"] },
  { name: "IBK기업은행", industry: "금융", mark: "IBK", color: "#0068B7", bg: "#FFFFFF", aliases: ["ibk", "기업은행", "기은"] },
  { name: "NH농협은행", industry: "금융", mark: "NH Bank", color: "#009A44", bg: "#FFFFFF", aliases: ["nh", "농협"] },
  { name: "카카오뱅크", industry: "금융", mark: "kakaobank", color: "#000000", bg: "#FFE300", aliases: ["kakaobank", "카뱅"] },
  { name: "케이뱅크", industry: "금융", mark: "K bank", color: "#1B64DA", bg: "#FFFFFF", aliases: ["kbank", "케뱅"] },
  { name: "토스뱅크", industry: "금융", mark: "Toss Bank", color: "#0064FF", bg: "#FFFFFF", aliases: ["tossbank", "토뱅"] },
  { name: "미래에셋증권", industry: "금융", mark: "MiraeAsset", color: "#F58220", bg: "#FFFFFF", aliases: ["miraeasset", "미래에셋"] },
  { name: "한국투자증권", industry: "금융", mark: "Korea Investment", color: "#003263", bg: "#FFFFFF", aliases: ["koreainvestment", "한투"] },
  { name: "NH투자증권", industry: "금융", mark: "NH투자증권", color: "#009A44", bg: "#FFFFFF", aliases: ["namuh", "나무증권"] },
  { name: "KB증권", industry: "금융", mark: "KB증권", color: "#FFA800", bg: "#FFFFFF", aliases: ["kbsec", "kb증권"] },
  { name: "삼성증권", industry: "금융", mark: "삼성증권", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsungsecurities", "삼증"] },
  { name: "키움증권", industry: "금융", mark: "키움증권", color: "#632E8E", bg: "#FFFFFF", aliases: ["kiwoom", "영웅문"] },
  { name: "신한투자증권", industry: "금융", mark: "신한투자증권", color: "#0046FF", bg: "#FFFFFF", aliases: ["shinhansec", "신한금투"] },
  { name: "메리츠증권", industry: "금융", mark: "메리츠증권", color: "#E4002B", bg: "#FFFFFF", aliases: ["meritz", "메리츠"] },
  { name: "토스증권", industry: "금융", mark: "Toss Securities", color: "#0064FF", bg: "#FFFFFF", aliases: ["tosssecurities", "토증"] },
  { name: "삼성생명", industry: "금융", mark: "삼성생명", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsunglife"] },
  { name: "삼성화재", industry: "금융", mark: "삼성화재", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsungfire"] },
  { name: "한화생명", industry: "금융", mark: "한화생명", color: "#F37321", bg: "#FFFFFF", aliases: ["hanwhalife"] },
  { name: "교보생명", industry: "금융", mark: "교보생명", color: "#036B3F", bg: "#FFFFFF", aliases: ["kyobo", "교보"] },
  { name: "DB손해보험", industry: "금융", mark: "DB손해보험", color: "#008C44", bg: "#FFFFFF", aliases: ["dbins", "db손보"] },
  { name: "현대해상", industry: "금융", mark: "현대해상", color: "#F26522", bg: "#FFFFFF", aliases: ["hyundaimarine", "하이카"] },
  { name: "KB손해보험", industry: "금융", mark: "KB손해보험", color: "#FFA800", bg: "#FFFFFF", aliases: ["kbins", "kb손보"] },
  { name: "메리츠화재", industry: "금융", mark: "메리츠화재", color: "#E4002B", bg: "#FFFFFF", aliases: ["meritzfire"] },
  { name: "신한카드", industry: "금융", mark: "Shinhan Card", color: "#0046FF", bg: "#FFFFFF", aliases: ["shinhancard"] },
  { name: "삼성카드", industry: "금융", mark: "Samsung Card", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsungcard"] },
  { name: "현대카드", industry: "금융", mark: "Hyundai Card", color: "#000000", bg: "#FFFFFF", aliases: ["hyundaicard"] },
  { name: "KB국민카드", industry: "금융", mark: "KB국민카드", color: "#FFA800", bg: "#FFFFFF", aliases: ["kbcard", "국민카드"] },
  { name: "롯데카드", industry: "금융", mark: "LOTTE CARD", color: "#DA291C", bg: "#FFFFFF", aliases: ["lottecard", "로카"] },
  { name: "우리카드", industry: "금융", mark: "우리카드", color: "#0067AC", bg: "#FFFFFF", aliases: ["wooricard"] },
  { name: "하나카드", industry: "금융", mark: "하나카드", color: "#008485", bg: "#FFFFFF", aliases: ["hanacard"] },
  { name: "BC카드", industry: "금융", mark: "BC card", color: "#DF1F26", bg: "#FFFFFF", aliases: ["bccard", "비씨카드"] },

  // ── 화학·에너지 ──────────────────────────────────────────
  { name: "LG화학", industry: "화학·에너지", mark: "LG Chem", color: "#A50034", bg: "#FFFFFF", aliases: ["lgchem"] },
  { name: "LG에너지솔루션", industry: "화학·에너지", mark: "LG Energy Solution", color: "#A50034", bg: "#FFFFFF", aliases: ["lges", "엔솔"] },
  { name: "삼성SDI", industry: "화학·에너지", mark: "Samsung SDI", color: "#1428A0", bg: "#FFFFFF", aliases: ["sdi", "samsungsdi"] },
  { name: "SK이노베이션", industry: "화학·에너지", mark: "SK innovation", color: "#EA002C", bg: "#FFFFFF", aliases: ["skinnovation", "스이노"] },
  { name: "SK온", industry: "화학·에너지", mark: "SK on", color: "#EA002C", bg: "#FFFFFF", aliases: ["skon"] },
  { name: "S-OIL", industry: "화학·에너지", mark: "S-OIL", color: "#F2A900", bg: "#FFFFFF", aliases: ["soil", "에쓰오일"] },
  { name: "GS칼텍스", industry: "화학·에너지", mark: "GS Caltex", color: "#007A33", bg: "#FFFFFF", aliases: ["gscaltex", "칼텍스"] },
  { name: "HD현대오일뱅크", industry: "화학·에너지", mark: "HD HYUNDAI OILBANK", color: "#00A651", bg: "#FFFFFF", aliases: ["oilbank", "오일뱅크"] },
  { name: "롯데케미칼", industry: "화학·에너지", mark: "LOTTE Chemical", color: "#DA291C", bg: "#FFFFFF", aliases: ["lottechem", "롯케"] },
  { name: "한화솔루션", industry: "화학·에너지", mark: "Hanwha Solutions", color: "#F37321", bg: "#FFFFFF", aliases: ["hanwhasolutions", "qcells", "큐셀"] },
  { name: "금호석유화학", industry: "화학·에너지", mark: "Kumho Petrochemical", color: "#D71920", bg: "#FFFFFF", aliases: ["kkpc", "금호석화"] },
  { name: "코오롱인더스트리", industry: "화학·에너지", mark: "KOLON Industries", color: "#1F286F", bg: "#FFFFFF", aliases: ["kolon", "코오롱"] },
  { name: "포스코퓨처엠", industry: "화학·에너지", mark: "POSCO FUTURE M", color: "#05507D", bg: "#FFFFFF", aliases: ["poscofuturem", "퓨처엠"] },
  { name: "에코프로비엠", industry: "화학·에너지", mark: "EcoPro BM", color: "#00A88E", bg: "#FFFFFF", aliases: ["ecopro", "에코프로"] },
  { name: "SKC", industry: "화학·에너지", mark: "SKC", color: "#EA002C", bg: "#FFFFFF", aliases: ["skc"] },

  // ── 유통·식품 ────────────────────────────────────────────
  { name: "이마트", industry: "유통·식품", mark: "emart", color: "#F5A623", bg: "#FFFFFF", aliases: ["emart"] },
  { name: "신세계", industry: "유통·식품", mark: "SHINSEGAE", color: "#C8102E", bg: "#FFFFFF", aliases: ["shinsegae", "ssg"] },
  { name: "롯데쇼핑", industry: "유통·식품", mark: "LOTTE Shopping", color: "#DA291C", bg: "#FFFFFF", aliases: ["lotteshopping", "롯데백화점", "롯백"] },
  { name: "현대백화점", industry: "유통·식품", mark: "The Hyundai", color: "#000000", bg: "#FFFFFF", aliases: ["thehyundai", "더현대", "현백"] },
  { name: "GS리테일", industry: "유통·식품", mark: "GS Retail", color: "#0072BC", bg: "#FFFFFF", aliases: ["gsretail", "gs25"] },
  { name: "BGF리테일", industry: "유통·식품", mark: "BGF retail", color: "#652F8E", bg: "#FFFFFF", aliases: ["bgf", "cu", "씨유"] },
  { name: "CJ올리브영", industry: "유통·식품", mark: "OLIVE YOUNG", color: "#9BCE26", bg: "#FFFFFF", aliases: ["oliveyoung", "올영"] },
  { name: "호텔신라", industry: "유통·식품", mark: "The Shilla", color: "#8A7048", bg: "#FFFFFF", aliases: ["shilla", "신라면세점"] },
  { name: "스타벅스코리아", industry: "유통·식품", mark: "STARBUCKS", color: "#00704A", bg: "#FFFFFF", aliases: ["starbucks", "sck", "스벅"] },
  { name: "CJ제일제당", industry: "유통·식품", mark: "CJ CheilJedang", color: "#ED1C24", bg: "#FFFFFF", aliases: ["cj", "제일제당"] },
  { name: "오뚜기", industry: "유통·식품", mark: "Ottogi", color: "#F2B233", bg: "#FFFFFF", aliases: ["ottogi"] },
  { name: "농심", industry: "유통·식품", mark: "NONGSHIM", color: "#E60012", bg: "#FFFFFF", aliases: ["nongshim", "신라면"] },
  { name: "삼양식품", industry: "유통·식품", mark: "SAMYANG", color: "#E4002B", bg: "#FFFFFF", aliases: ["samyang", "불닭"] },
  { name: "오리온", industry: "유통·식품", mark: "ORION", color: "#DA1F26", bg: "#FFFFFF", aliases: ["orion", "초코파이"] },
  { name: "빙그레", industry: "유통·식품", mark: "Binggrae", color: "#F05123", bg: "#FFFFFF", aliases: ["binggrae", "바나나맛우유"] },
  { name: "동원F&B", industry: "유통·식품", mark: "Dongwon", color: "#008C95", bg: "#FFFFFF", aliases: ["dongwon", "동원참치"] },
  { name: "풀무원", industry: "유통·식품", mark: "Pulmuone", color: "#00A44F", bg: "#FFFFFF", aliases: ["pulmuone"] },
  { name: "매일유업", industry: "유통·식품", mark: "Maeil", color: "#0057A8", bg: "#FFFFFF", aliases: ["maeil"] },
  { name: "SPC삼립", industry: "유통·식품", mark: "SPC Samlip", color: "#ED1B2F", bg: "#FFFFFF", aliases: ["spc", "삼립", "파리바게뜨"] },
  { name: "롯데웰푸드", industry: "유통·식품", mark: "LOTTE Wellfood", color: "#DA291C", bg: "#FFFFFF", aliases: ["lottewellfood", "롯데제과"] },
  { name: "롯데칠성음료", industry: "유통·식품", mark: "LOTTE Chilsung", color: "#DA291C", bg: "#FFFFFF", aliases: ["lottechilsung", "칠성사이다"] },
  { name: "하이트진로", industry: "유통·식품", mark: "HITEJINRO", color: "#005BAC", bg: "#FFFFFF", aliases: ["hitejinro", "참이슬", "테라"] },
  { name: "KT&G", industry: "유통·식품", mark: "KT&G", color: "#004B93", bg: "#FFFFFF", aliases: ["ktng", "케이티앤지"] },
  { name: "아모레퍼시픽", industry: "유통·식품", mark: "AMOREPACIFIC", color: "#C2185B", bg: "#FFFFFF", aliases: ["amorepacific", "아모레"] },
  { name: "LG생활건강", industry: "유통·식품", mark: "LG H&H", color: "#A50034", bg: "#FFFFFF", aliases: ["lghnh", "엘지생건"] },

  // ── 제약·바이오 ──────────────────────────────────────────
  { name: "셀트리온", industry: "제약·바이오", mark: "CELLTRION", color: "#009A4E", bg: "#FFFFFF", aliases: ["celltrion", "셀트"] },
  { name: "삼성바이오로직스", industry: "제약·바이오", mark: "Samsung Biologics", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsungbiologics", "삼바"] },
  { name: "삼성바이오에피스", industry: "제약·바이오", mark: "Samsung Bioepis", color: "#1428A0", bg: "#FFFFFF", aliases: ["bioepis", "에피스"] },
  { name: "유한양행", industry: "제약·바이오", mark: "Yuhan", color: "#0072BC", bg: "#FFFFFF", aliases: ["yuhan"] },
  { name: "GC녹십자", industry: "제약·바이오", mark: "GC Biopharma", color: "#00843D", bg: "#FFFFFF", aliases: ["greencross", "녹십자"] },
  { name: "한미약품", industry: "제약·바이오", mark: "Hanmi", color: "#F26F21", bg: "#FFFFFF", aliases: ["hanmi"] },
  { name: "종근당", industry: "제약·바이오", mark: "CKD", color: "#046A38", bg: "#FFFFFF", aliases: ["ckdpharm", "ckd"] },
  { name: "대웅제약", industry: "제약·바이오", mark: "Daewoong", color: "#F57F29", bg: "#FFFFFF", aliases: ["daewoong", "우루사"] },
  { name: "동아ST", industry: "제약·바이오", mark: "Dong-A ST", color: "#0077C8", bg: "#FFFFFF", aliases: ["dongast", "박카스"] },
  { name: "보령", industry: "제약·바이오", mark: "Boryung", color: "#00B0B9", bg: "#FFFFFF", aliases: ["boryung", "보령제약"] },
  { name: "HK이노엔", industry: "제약·바이오", mark: "HK inno.N", color: "#E8541E", bg: "#FFFFFF", aliases: ["innon", "컨디션"] },
  { name: "SK바이오팜", industry: "제약·바이오", mark: "SK biopharmaceuticals", color: "#EA002C", bg: "#FFFFFF", aliases: ["skbiopharm"] },
  { name: "SK바이오사이언스", industry: "제약·바이오", mark: "SK bioscience", color: "#EA002C", bg: "#FFFFFF", aliases: ["skbioscience", "스바사"] },
  { name: "휴젤", industry: "제약·바이오", mark: "Hugel", color: "#6A2C91", bg: "#FFFFFF", aliases: ["hugel"] },

  // ── 자동차·중공업 ────────────────────────────────────────
  { name: "현대자동차", industry: "자동차·중공업", mark: "HYUNDAI", color: "#002C5F", bg: "#FFFFFF", aliases: ["hyundai", "현차", "현대차"] },
  { name: "기아", industry: "자동차·중공업", mark: "KIA", color: "#05141F", bg: "#FFFFFF", aliases: ["kia", "기아차"] },
  { name: "현대모비스", industry: "자동차·중공업", mark: "MOBIS", color: "#002C5F", bg: "#FFFFFF", aliases: ["mobis", "모비스"] },
  { name: "현대위아", industry: "자동차·중공업", mark: "HYUNDAI WIA", color: "#002C5F", bg: "#FFFFFF", aliases: ["wia", "위아"] },
  { name: "현대트랜시스", industry: "자동차·중공업", mark: "HYUNDAI TRANSYS", color: "#002C5F", bg: "#FFFFFF", aliases: ["transys", "트랜시스"] },
  { name: "HL만도", industry: "자동차·중공업", mark: "HL Mando", color: "#00A9B5", bg: "#FFFFFF", aliases: ["mando", "만도"] },
  { name: "현대제철", industry: "자동차·중공업", mark: "HYUNDAI Steel", color: "#002C5F", bg: "#FFFFFF", aliases: ["hyundaisteel"] },
  { name: "포스코", industry: "자동차·중공업", mark: "POSCO", color: "#05507D", bg: "#FFFFFF", aliases: ["posco", "포철"] },
  { name: "고려아연", industry: "자동차·중공업", mark: "Korea Zinc", color: "#005EB8", bg: "#FFFFFF", aliases: ["koreazinc"] },
  { name: "HD현대중공업", industry: "자동차·중공업", mark: "HD HYUNDAI", color: "#00A651", bg: "#FFFFFF", aliases: ["hdhyundai", "현중"] },
  { name: "HD한국조선해양", industry: "자동차·중공업", mark: "HD KSOE", color: "#00A651", bg: "#FFFFFF", aliases: ["ksoe", "조선해양"] },
  { name: "HD현대인프라코어", industry: "자동차·중공업", mark: "HD HYUNDAI INFRACORE", color: "#00A651", bg: "#FFFFFF", aliases: ["infracore", "인프라코어"] },
  { name: "한화오션", industry: "자동차·중공업", mark: "Hanwha Ocean", color: "#F37321", bg: "#FFFFFF", aliases: ["hanwhaocean", "대우조선"] },
  { name: "삼성중공업", industry: "자동차·중공업", mark: "Samsung Heavy Industries", color: "#1428A0", bg: "#FFFFFF", aliases: ["shi", "삼중"] },
  { name: "두산에너빌리티", industry: "자동차·중공업", mark: "Doosan Enerbility", color: "#1A428A", bg: "#FFFFFF", aliases: ["doosan", "에너빌리티", "두산중공업"] },
  { name: "두산밥캣", industry: "자동차·중공업", mark: "Doosan Bobcat", color: "#FF3600", bg: "#FFFFFF", aliases: ["bobcat", "밥캣"] },
  { name: "두산로보틱스", industry: "자동차·중공업", mark: "Doosan Robotics", color: "#1A428A", bg: "#FFFFFF", aliases: ["doosanrobotics"] },
  { name: "한화에어로스페이스", industry: "자동차·중공업", mark: "Hanwha Aerospace", color: "#F37321", bg: "#FFFFFF", aliases: ["hanwhaaerospace", "한화에어로"] },
  { name: "한국항공우주산업", industry: "자동차·중공업", mark: "KAI", color: "#005BAB", bg: "#FFFFFF", aliases: ["kai", "카이"] },
  { name: "LIG넥스원", industry: "자동차·중공업", mark: "LIG Nex1", color: "#A6192E", bg: "#FFFFFF", aliases: ["lignex1", "넥스원"] },
  { name: "현대로템", industry: "자동차·중공업", mark: "HYUNDAI ROTEM", color: "#002C5F", bg: "#FFFFFF", aliases: ["rotem", "로템"] },

  // ── 건설 ─────────────────────────────────────────────────
  { name: "삼성물산", industry: "건설", mark: "Samsung C&T", color: "#1428A0", bg: "#FFFFFF", aliases: ["samsungcnt", "물산", "래미안"] },
  { name: "현대건설", industry: "건설", mark: "HYUNDAI E&C", color: "#002C5F", bg: "#FFFFFF", aliases: ["hdec", "힐스테이트"] },
  { name: "현대엔지니어링", industry: "건설", mark: "HYUNDAI Engineering", color: "#002C5F", bg: "#FFFFFF", aliases: ["hec", "현대엔지"] },
  { name: "GS건설", industry: "건설", mark: "GS E&C", color: "#0072BC", bg: "#FFFFFF", aliases: ["gsenc", "자이"] },
  { name: "대우건설", industry: "건설", mark: "DAEWOO E&C", color: "#0066B3", bg: "#FFFFFF", aliases: ["daewooenc", "푸르지오"] },
  { name: "DL이앤씨", industry: "건설", mark: "DL E&C", color: "#0E2B5C", bg: "#FFFFFF", aliases: ["dlenc", "이편한세상", "대림"] },
  { name: "포스코이앤씨", industry: "건설", mark: "POSCO E&C", color: "#05507D", bg: "#FFFFFF", aliases: ["poscoenc", "더샵"] },
  { name: "롯데건설", industry: "건설", mark: "LOTTE E&C", color: "#DA291C", bg: "#FFFFFF", aliases: ["lotteenc", "롯데캐슬"] },
  { name: "SK에코플랜트", industry: "건설", mark: "SK ecoplant", color: "#3DA32E", bg: "#FFFFFF", aliases: ["ecoplant", "sk건설"] },
  { name: "HDC현대산업개발", industry: "건설", mark: "HDC", color: "#003469", bg: "#FFFFFF", aliases: ["hdc", "아이파크"] },

  // ── 통신 ─────────────────────────────────────────────────
  { name: "SK텔레콤", industry: "통신", mark: "SK telecom", color: "#EA002C", bg: "#FFFFFF", aliases: ["skt", "에스케이텔레콤"] },
  { name: "KT", industry: "통신", mark: "kt", color: "#E4002B", bg: "#FFFFFF", aliases: ["kt", "케이티"] },
  { name: "LG유플러스", industry: "통신", mark: "LG U+", color: "#ED008C", bg: "#FFFFFF", aliases: ["lguplus", "uplus", "유플"] },
  { name: "SK브로드밴드", industry: "통신", mark: "SK broadband", color: "#EA002C", bg: "#FFFFFF", aliases: ["skb", "브로드밴드"] },

  // ── 항공·운송 ────────────────────────────────────────────
  { name: "대한항공", industry: "항공·운송", mark: "KOREAN AIR", color: "#0F4C96", bg: "#FFFFFF", aliases: ["koreanair", "kal", "대항"] },
  { name: "아시아나항공", industry: "항공·운송", mark: "ASIANA AIRLINES", color: "#D4002A", bg: "#FFFFFF", aliases: ["asiana", "oz"] },
  { name: "제주항공", industry: "항공·운송", mark: "JEJU air", color: "#FF5A00", bg: "#FFFFFF", aliases: ["jejuair", "7c"] },
  { name: "진에어", industry: "항공·운송", mark: "JIN AIR", color: "#8DC63F", bg: "#FFFFFF", aliases: ["jinair", "lj"] },
  { name: "티웨이항공", industry: "항공·운송", mark: "t'way", color: "#E51937", bg: "#FFFFFF", aliases: ["tway", "tw"] },
  { name: "HMM", industry: "항공·운송", mark: "HMM", color: "#EA1B2D", bg: "#FFFFFF", aliases: ["hmm", "현대상선"] },
  { name: "CJ대한통운", industry: "항공·운송", mark: "CJ Logistics", color: "#ED1C24", bg: "#FFFFFF", aliases: ["cjlogistics", "대한통운"] },
  { name: "한진", industry: "항공·운송", mark: "HANJIN", color: "#0054A6", bg: "#FFFFFF", aliases: ["hanjin", "한진택배"] },
  { name: "현대글로비스", industry: "항공·운송", mark: "HYUNDAI GLOVIS", color: "#002C5F", bg: "#FFFFFF", aliases: ["glovis", "글로비스"] },
  { name: "롯데글로벌로지스", industry: "항공·운송", mark: "LOTTE Global Logistics", color: "#DA291C", bg: "#FFFFFF", aliases: ["lotteglogis", "롯데택배"] },

  // ── 공기업 ───────────────────────────────────────────────
  { name: "한국전력공사", industry: "공기업", mark: "KEPCO", color: "#0055B8", bg: "#FFFFFF", aliases: ["kepco", "한전"] },
  { name: "한국수력원자력", industry: "공기업", mark: "KHNP", color: "#0066B3", bg: "#FFFFFF", aliases: ["khnp", "한수원"] },
  { name: "한국가스공사", industry: "공기업", mark: "KOGAS", color: "#0063A7", bg: "#FFFFFF", aliases: ["kogas", "가스공사"] },
  { name: "한국도로공사", industry: "공기업", mark: "ex", color: "#0075C8", bg: "#FFFFFF", aliases: ["ex", "도로공사", "도공"] },
  { name: "한국수자원공사", industry: "공기업", mark: "K-water", color: "#005EB8", bg: "#FFFFFF", aliases: ["kwater", "수자원공사", "수공"] },
  { name: "한국철도공사", industry: "공기업", mark: "KORAIL", color: "#005BAC", bg: "#FFFFFF", aliases: ["korail", "코레일"] },
  { name: "인천국제공항공사", industry: "공기업", mark: "Incheon Airport", color: "#005595", bg: "#FFFFFF", aliases: ["iiac", "인천공항"] },
  { name: "한국공항공사", industry: "공기업", mark: "KAC", color: "#0072BC", bg: "#FFFFFF", aliases: ["kac", "공항공사"] },
  { name: "한국토지주택공사", industry: "공기업", mark: "LH", color: "#00A650", bg: "#FFFFFF", aliases: ["lh", "토지주택공사"] },
  { name: "국민건강보험공단", industry: "공기업", mark: "NHIS", color: "#1D6FB8", bg: "#FFFFFF", aliases: ["nhis", "건보공단", "건보"] },
  { name: "국민연금공단", industry: "공기업", mark: "NPS", color: "#0C4DA2", bg: "#FFFFFF", aliases: ["nps", "연금공단"] },
  { name: "근로복지공단", industry: "공기업", mark: "COMWEL", color: "#2A5CAA", bg: "#FFFFFF", aliases: ["comwel", "근복"] },
  { name: "서울교통공사", industry: "공기업", mark: "Seoul Metro", color: "#00A5DE", bg: "#FFFFFF", aliases: ["seoulmetro", "교통공사"] },
  { name: "KDB산업은행", industry: "공기업", mark: "KDB", color: "#003E7E", bg: "#FFFFFF", aliases: ["kdb", "산업은행", "산은"] },
  { name: "한국수출입은행", industry: "공기업", mark: "Korea Eximbank", color: "#00529C", bg: "#FFFFFF", aliases: ["eximbank", "수출입은행", "수은"] },

  // ── 미디어 ───────────────────────────────────────────────
  { name: "CJ ENM", industry: "미디어", mark: "CJ ENM", color: "#ED1C24", bg: "#FFFFFF", aliases: ["cjenm", "tvn"] },
  { name: "스튜디오드래곤", industry: "미디어", mark: "STUDIO DRAGON", color: "#4B21A6", bg: "#FFFFFF", aliases: ["studiodragon"] },
  { name: "티빙", industry: "미디어", mark: "TVING", color: "#FF153C", bg: "#FFFFFF", aliases: ["tving"] },
  { name: "SBS", industry: "미디어", mark: "SBS", color: "#0046A0", bg: "#FFFFFF", aliases: ["sbs", "에스비에스"] },
  { name: "MBC", industry: "미디어", mark: "MBC", color: "#D6001C", bg: "#FFFFFF", aliases: ["mbc", "문화방송"] },
  { name: "KBS", industry: "미디어", mark: "KBS", color: "#144C94", bg: "#FFFFFF", aliases: ["kbs", "한국방송"] },
  { name: "JTBC", industry: "미디어", mark: "JTBC", color: "#B60028", bg: "#FFFFFF", aliases: ["jtbc", "제이티비씨"] },
  { name: "하이브", industry: "미디어", mark: "HYBE", color: "#000000", bg: "#FFFFFF", aliases: ["hybe", "빅히트"] },
  { name: "SM엔터테인먼트", industry: "미디어", mark: "SM Entertainment", color: "#ED0973", bg: "#FFFFFF", aliases: ["smtown", "sm엔터"] },
  { name: "JYP엔터테인먼트", industry: "미디어", mark: "JYP", color: "#333333", bg: "#FFFFFF", aliases: ["jyp", "제이와이피"] },
  { name: "YG엔터테인먼트", industry: "미디어", mark: "YG", color: "#000000", bg: "#FFFFFF", aliases: ["yg", "와이지"] },
  { name: "CJ CGV", industry: "미디어", mark: "CGV", color: "#E71A0F", bg: "#FFFFFF", aliases: ["cgv", "씨지비"] },
  { name: "카카오엔터테인먼트", industry: "미디어", mark: "kakao entertainment", color: "#000000", bg: "#FEE500", aliases: ["kakaoent", "카카오엔터"] },

  // ── 2026-10-09 추가: 계열사·클라우드/SI·AI·반도체·공공기관·대전 지역 ──
  { name: "KT클라우드", industry: "클라우드·SI", mark: "kt cloud", color: "#E4002B", bg: "#FFFFFF", aliases: ["ktcloud", "케이티클라우드", "kt클라우드"] },
  { name: "KT DS", industry: "클라우드·SI", mark: "kt ds", color: "#E4002B", bg: "#FFFFFF", aliases: ["ktds", "케이티디에스"] },
  { name: "KT스카이라이프", industry: "미디어", mark: "kt skylife", color: "#E4002B", bg: "#FFFFFF", aliases: ["skylife", "스카이라이프"] },
  { name: "SK AX", industry: "클라우드·SI", mark: "SK AX", color: "#EA002C", bg: "#FFFFFF", aliases: ["skax", "skc&c", "skcc", "sk씨앤씨"] },
  { name: "SK쉴더스", industry: "클라우드·SI", mark: "SK shieldus", color: "#EA002C", bg: "#FFFFFF", aliases: ["shieldus", "skshieldus", "adt캡스"] },
  { name: "SK플래닛", industry: "플랫폼", mark: "SK planet", color: "#EA002C", bg: "#FFFFFF", aliases: ["skplanet", "ok캐쉬백"] },
  { name: "11번가", industry: "플랫폼", mark: "11st", color: "#FF0038", bg: "#FFFFFF", aliases: ["11st", "십일번가"] },
  { name: "LG헬로비전", industry: "미디어", mark: "LG HelloVision", color: "#A50034", bg: "#FFFFFF", aliases: ["hellovision", "헬로비전"] },
  { name: "LX세미콘", industry: "반도체", mark: "LX Semicon", color: "#004A99", bg: "#FFFFFF", aliases: ["lxsemicon"] },
  { name: "LX인터내셔널", industry: "유통·식품", mark: "LX International", color: "#004A99", bg: "#FFFFFF", aliases: ["lxinternational"] },
  { name: "CJ올리브네트웍스", industry: "클라우드·SI", mark: "CJ OliveNetworks", color: "#F15A22", bg: "#FFFFFF", aliases: ["cjolivenetworks", "올리브네트웍스"] },
  { name: "신세계I&C", industry: "클라우드·SI", mark: "SHINSEGAE I&C", color: "#C8102E", bg: "#FFFFFF", aliases: ["신세계아이앤씨", "ssgic"] },
  { name: "현대IT&E", industry: "클라우드·SI", mark: "HYUNDAI IT&E", color: "#2E5E4E", bg: "#FFFFFF", aliases: ["현대아이티앤이"] },
  { name: "한화비전", industry: "전자·IT", mark: "Hanwha Vision", color: "#F37321", bg: "#FFFFFF", aliases: ["hanwhavision", "한화테크윈"] },
  { name: "메가존클라우드", industry: "클라우드·SI", mark: "MEGAZONECLOUD", color: "#4E2A84", bg: "#FFFFFF", aliases: ["megazone", "메가존"] },
  { name: "베스핀글로벌", industry: "클라우드·SI", mark: "BESPIN GLOBAL", color: "#00A0E9", bg: "#FFFFFF", aliases: ["bespin", "베스핀"] },
  { name: "NHN클라우드", industry: "클라우드·SI", mark: "NHN Cloud", color: "#00A24C", bg: "#FFFFFF", aliases: ["nhncloud"] },
  { name: "GS네오텍", industry: "클라우드·SI", mark: "GS Neotek", color: "#00A0B0", bg: "#FFFFFF", aliases: ["gsneotek"] },
  { name: "가비아", industry: "클라우드·SI", mark: "gabia", color: "#1F64F0", bg: "#FFFFFF", aliases: ["gabia"] },
  { name: "카카오엔터프라이즈", industry: "클라우드·SI", mark: "kakao enterprise", color: "#000000", bg: "#FFFFFF", aliases: ["kakaoenterprise", "카카오클라우드"] },
  { name: "더존비즈온", industry: "클라우드·SI", mark: "DOUZONE", color: "#0062B1", bg: "#FFFFFF", aliases: ["douzone", "더존"] },
  { name: "티맥스소프트", industry: "클라우드·SI", mark: "TmaxSoft", color: "#D7282F", bg: "#FFFFFF", aliases: ["tmax", "티맥스"] },
  { name: "다우기술", industry: "클라우드·SI", mark: "DAOU", color: "#0A3C7D", bg: "#FFFFFF", aliases: ["daou", "다우"] },
  { name: "쌍용정보통신", industry: "클라우드·SI", mark: "SsangYong ICT", color: "#333D4B", bg: "#FFFFFF", aliases: ["sicc", "쌍용ict"] },
  { name: "아이티센", industry: "클라우드·SI", mark: "ITCEN", color: "#333D4B", bg: "#FFFFFF", aliases: ["itcen"] },
  { name: "한전KDN", industry: "공기업", mark: "KDN", color: "#0067AC", bg: "#FFFFFF", aliases: ["kdn", "한전케이디엔"] },
  { name: "코스콤", industry: "금융", mark: "KOSCOM", color: "#003C8F", bg: "#FFFFFF", aliases: ["koscom"] },
  { name: "금융결제원", industry: "금융", mark: "KFTC", color: "#004EA2", bg: "#FFFFFF", aliases: ["kftc"] },
  { name: "하나금융티아이", industry: "클라우드·SI", mark: "Hana TI", color: "#008485", bg: "#FFFFFF", aliases: ["하나금융ti", "hanati"] },
  { name: "신한DS", industry: "클라우드·SI", mark: "Shinhan DS", color: "#0046FF", bg: "#FFFFFF", aliases: ["shinhands"] },
  { name: "KB데이타시스템", industry: "클라우드·SI", mark: "KB DS", color: "#FFBC00", bg: "#FFFFFF", aliases: ["kbds", "kb데이터시스템"] },
  { name: "농협정보시스템", industry: "클라우드·SI", mark: "NH IS", color: "#00A651", bg: "#FFFFFF", aliases: ["nhis", "농협정보"] },
  { name: "이스트소프트", industry: "전자·IT", mark: "ESTsoft", color: "#1A73E8", bg: "#FFFFFF", aliases: ["estsoft", "알약"] },
  { name: "웹케시", industry: "클라우드·SI", mark: "Webcash", color: "#333D4B", bg: "#FFFFFF", aliases: ["webcash"] },
  { name: "NICE평가정보", industry: "금융", mark: "NICE", color: "#003A70", bg: "#FFFFFF", aliases: ["nice", "나이스"] },
  { name: "마이다스아이티", industry: "전자·IT", mark: "MIDAS IT", color: "#0072BC", bg: "#FFFFFF", aliases: ["midasit", "마이다스"] },
  { name: "업스테이지", industry: "AI", mark: "Upstage", color: "#7B2FF7", bg: "#FFFFFF", aliases: ["upstage"] },
  { name: "뤼튼테크놀로지스", industry: "AI", mark: "wrtn", color: "#5A2BE2", bg: "#FFFFFF", aliases: ["wrtn", "뤼튼"] },
  { name: "리벨리온", industry: "반도체", mark: "REBELLIONS", color: "#333D4B", bg: "#FFFFFF", aliases: ["rebellions"] },
  { name: "퓨리오사AI", industry: "반도체", mark: "FuriosaAI", color: "#333D4B", bg: "#FFFFFF", aliases: ["furiosa", "퓨리오사"] },
  { name: "포티투닷", industry: "AI", mark: "42dot", color: "#333D4B", bg: "#FFFFFF", aliases: ["42dot"] },
  { name: "마키나락스", industry: "AI", mark: "MakinaRocks", color: "#333D4B", bg: "#FFFFFF", aliases: ["makinarocks"] },
  { name: "스캐터랩", industry: "AI", mark: "Scatter Lab", color: "#FF5A5F", bg: "#FFFFFF", aliases: ["scatterlab", "이루다"] },
  { name: "루닛", industry: "AI", mark: "Lunit", color: "#00B2A9", bg: "#FFFFFF", aliases: ["lunit"] },
  { name: "뷰노", industry: "AI", mark: "VUNO", color: "#0055B8", bg: "#FFFFFF", aliases: ["vuno"] },
  { name: "솔트룩스", industry: "AI", mark: "Saltlux", color: "#E2231A", bg: "#FFFFFF", aliases: ["saltlux"] },
  { name: "코난테크놀로지", industry: "AI", mark: "KONAN", color: "#333D4B", bg: "#FFFFFF", aliases: ["konan"] },
  { name: "셀바스AI", industry: "AI", mark: "SELVAS AI", color: "#333D4B", bg: "#FFFFFF", aliases: ["selvas"] },
  { name: "하이퍼커넥트", industry: "플랫폼", mark: "Hyperconnect", color: "#00C4CC", bg: "#FFFFFF", aliases: ["hyperconnect", "아자르"] },
  { name: "여기어때컴퍼니", industry: "플랫폼", mark: "여기어때", color: "#E6006E", bg: "#FFFFFF", aliases: ["여기어때", "goodchoice"] },
  { name: "SK실트론", industry: "반도체", mark: "SK siltron", color: "#EA002C", bg: "#FFFFFF", aliases: ["siltron", "실트론"] },
  { name: "한미반도체", industry: "반도체", mark: "HANMI", color: "#0054A6", bg: "#FFFFFF", aliases: ["hanmisemi"] },
  { name: "원익IPS", industry: "반도체", mark: "WONIK IPS", color: "#003DA5", bg: "#FFFFFF", aliases: ["wonikips", "원익"] },
  { name: "주성엔지니어링", industry: "반도체", mark: "JUSUNG", color: "#0068B7", bg: "#FFFFFF", aliases: ["jusung"] },
  { name: "솔브레인", industry: "반도체", mark: "Soulbrain", color: "#333D4B", bg: "#FFFFFF", aliases: ["soulbrain"] },
  { name: "동진쎄미켐", industry: "반도체", mark: "DONGJIN", color: "#333D4B", bg: "#FFFFFF", aliases: ["dongjin", "동진세미켐"] },
  { name: "앰코테크놀로지코리아", industry: "반도체", mark: "Amkor", color: "#E31837", bg: "#FFFFFF", aliases: ["amkor", "앰코"] },
  { name: "삼성E&A", industry: "건설", mark: "Samsung E&A", color: "#1428A0", bg: "#FFFFFF", aliases: ["삼성엔지니어링", "samsungena"] },
  { name: "삼성웰스토리", industry: "유통·식품", mark: "Samsung Welstory", color: "#1428A0", bg: "#FFFFFF", aliases: ["welstory", "웰스토리"] },
  { name: "제일기획", industry: "미디어", mark: "Cheil", color: "#1428A0", bg: "#FFFFFF", aliases: ["cheil"] },
  { name: "에스원", industry: "전자·IT", mark: "S-1", color: "#1428A0", bg: "#FFFFFF", aliases: ["s1", "에스원"] },
  { name: "이노션", industry: "미디어", mark: "INNOCEAN", color: "#333D4B", bg: "#FFFFFF", aliases: ["innocean"] },
  { name: "CJ프레시웨이", industry: "유통·식품", mark: "CJ Freshway", color: "#F15A22", bg: "#FFFFFF", aliases: ["freshway"] },
  { name: "한국타이어앤테크놀로지", industry: "자동차·중공업", mark: "Hankook", color: "#F47920", bg: "#FFFFFF", aliases: ["hankook", "한국타이어"] },
  { name: "그라비티", industry: "게임", mark: "GRAVITY", color: "#333D4B", bg: "#FFFFFF", aliases: ["gravity", "라그나로크"] },
  { name: "웹젠", industry: "게임", mark: "WEBZEN", color: "#E60012", bg: "#FFFFFF", aliases: ["webzen"] },
  { name: "한국조폐공사", industry: "공기업", mark: "KOMSCO", color: "#004A8F", bg: "#FFFFFF", aliases: ["komsco", "조폐공사"] },
  { name: "국가철도공단", industry: "공기업", mark: "KR", color: "#0055A5", bg: "#FFFFFF", aliases: ["철도공단", "krna"] },
  { name: "에스알", industry: "공기업", mark: "SR", color: "#6B2C91", bg: "#FFFFFF", aliases: ["sr", "srt"] },
  { name: "한국가스기술공사", industry: "공기업", mark: "KOGAS-Tech", color: "#0072BC", bg: "#FFFFFF", aliases: ["가스기술공사", "kogastech"] },
  { name: "한전KPS", industry: "공기업", mark: "KEPCO KPS", color: "#0067AC", bg: "#FFFFFF", aliases: ["kps", "한전케이피에스"] },
  { name: "한국남부발전", industry: "공기업", mark: "KOSPO", color: "#0067AC", bg: "#FFFFFF", aliases: ["kospo", "남부발전"] },
  { name: "한국동서발전", industry: "공기업", mark: "EWP", color: "#0067AC", bg: "#FFFFFF", aliases: ["ewp", "동서발전"] },
  { name: "한국서부발전", industry: "공기업", mark: "KOWEPO", color: "#0067AC", bg: "#FFFFFF", aliases: ["kowepo", "서부발전"] },
  { name: "한국남동발전", industry: "공기업", mark: "KOEN", color: "#0067AC", bg: "#FFFFFF", aliases: ["koen", "남동발전"] },
  { name: "한국중부발전", industry: "공기업", mark: "KOMIPO", color: "#0067AC", bg: "#FFFFFF", aliases: ["komipo", "중부발전"] },
  { name: "한국지역난방공사", industry: "공기업", mark: "KDHC", color: "#E60012", bg: "#FFFFFF", aliases: ["kdhc", "지역난방공사"] },
  { name: "한국농어촌공사", industry: "공기업", mark: "KRC", color: "#00843D", bg: "#FFFFFF", aliases: ["krc", "농어촌공사"] },
  { name: "한국환경공단", industry: "공기업", mark: "K-eco", color: "#00A651", bg: "#FFFFFF", aliases: ["keco", "환경공단"] },
  { name: "한국부동산원", industry: "공기업", mark: "REB", color: "#0054A6", bg: "#FFFFFF", aliases: ["reb", "부동산원"] },
  { name: "주택도시보증공사", industry: "공기업", mark: "HUG", color: "#E4007F", bg: "#FFFFFF", aliases: ["hug"] },
  { name: "한국자산관리공사", industry: "공기업", mark: "KAMCO", color: "#0054A6", bg: "#FFFFFF", aliases: ["kamco", "캠코"] },
  { name: "신용보증기금", industry: "금융", mark: "KODIT", color: "#0054A6", bg: "#FFFFFF", aliases: ["kodit", "신보"] },
  { name: "기술보증기금", industry: "금융", mark: "KIBO", color: "#0054A6", bg: "#FFFFFF", aliases: ["kibo", "기보"] },
  { name: "한국무역보험공사", industry: "공기업", mark: "K-SURE", color: "#0054A6", bg: "#FFFFFF", aliases: ["ksure", "무역보험공사"] },
  { name: "중소벤처기업진흥공단", industry: "공기업", mark: "KOSME", color: "#0054A6", bg: "#FFFFFF", aliases: ["kosme", "중진공"] },
  { name: "한국인터넷진흥원", industry: "공공기관", mark: "KISA", color: "#0054A6", bg: "#FFFFFF", aliases: ["kisa"] },
  { name: "한국지능정보사회진흥원", industry: "공공기관", mark: "NIA", color: "#0054A6", bg: "#FFFFFF", aliases: ["nia"] },
  { name: "정보통신산업진흥원", industry: "공공기관", mark: "NIPA", color: "#0054A6", bg: "#FFFFFF", aliases: ["nipa"] },
  { name: "한국산업인력공단", industry: "공공기관", mark: "HRDK", color: "#0054A6", bg: "#FFFFFF", aliases: ["hrdk", "산업인력공단", "큐넷"] },
  { name: "한국관광공사", industry: "공기업", mark: "KTO", color: "#0054A6", bg: "#FFFFFF", aliases: ["kto", "관광공사"] },
  { name: "KOTRA", industry: "공공기관", mark: "KOTRA", color: "#0054A6", bg: "#FFFFFF", aliases: ["kotra", "코트라", "대한무역투자진흥공사"] },
  { name: "한국전기안전공사", industry: "공기업", mark: "KESCO", color: "#0054A6", bg: "#FFFFFF", aliases: ["kesco", "전기안전공사"] },
  { name: "한국마사회", industry: "공기업", mark: "KRA", color: "#00843D", bg: "#FFFFFF", aliases: ["kra", "마사회"] },
  { name: "강원랜드", industry: "공기업", mark: "KANGWON LAND", color: "#333D4B", bg: "#FFFFFF", aliases: ["kangwonland"] },
  { name: "한국전자통신연구원", industry: "연구기관", mark: "ETRI", color: "#0054A6", bg: "#FFFFFF", aliases: ["etri", "전자통신연구원"] },
  { name: "한국과학기술정보연구원", industry: "연구기관", mark: "KISTI", color: "#0054A6", bg: "#FFFFFF", aliases: ["kisti"] },
  { name: "한국항공우주연구원", industry: "연구기관", mark: "KARI", color: "#0054A6", bg: "#FFFFFF", aliases: ["kari", "항우연"] },
  { name: "한국원자력연구원", industry: "연구기관", mark: "KAERI", color: "#0054A6", bg: "#FFFFFF", aliases: ["kaeri", "원자력연"] },
  { name: "한국표준과학연구원", industry: "연구기관", mark: "KRISS", color: "#0054A6", bg: "#FFFFFF", aliases: ["kriss", "표준연"] },
  { name: "한국화학연구원", industry: "연구기관", mark: "KRICT", color: "#0054A6", bg: "#FFFFFF", aliases: ["krict", "화학연"] },
  { name: "한국생명공학연구원", industry: "연구기관", mark: "KRIBB", color: "#0054A6", bg: "#FFFFFF", aliases: ["kribb", "생명연"] },
  { name: "한국에너지기술연구원", industry: "연구기관", mark: "KIER", color: "#0054A6", bg: "#FFFFFF", aliases: ["kier", "에너지연"] },
  { name: "한국기계연구원", industry: "연구기관", mark: "KIMM", color: "#0054A6", bg: "#FFFFFF", aliases: ["kimm", "기계연"] },
  { name: "한국지질자원연구원", industry: "연구기관", mark: "KIGAM", color: "#0054A6", bg: "#FFFFFF", aliases: ["kigam", "지질연"] },
  { name: "한국천문연구원", industry: "연구기관", mark: "KASI", color: "#0054A6", bg: "#FFFFFF", aliases: ["kasi", "천문연"] },
  { name: "국방과학연구소", industry: "연구기관", mark: "ADD", color: "#0054A6", bg: "#FFFFFF", aliases: ["add", "국과연"] },
  { name: "국가보안기술연구소", industry: "연구기관", mark: "NSR", color: "#0054A6", bg: "#FFFFFF", aliases: ["nsr", "보안연"] },
  { name: "대전광역시청", industry: "공공기관", mark: "대전광역시", color: "#0054A6", bg: "#FFFFFF", aliases: ["대전시청", "대전시", "daejeon"] },
  { name: "충청남도청", industry: "공공기관", mark: "충청남도", color: "#0054A6", bg: "#FFFFFF", aliases: ["충남도청", "충남"] },
  { name: "대전도시공사", industry: "공기업", mark: "DCC", color: "#0054A6", bg: "#FFFFFF", aliases: ["dcc", "도시공사"] },
  { name: "대전교통공사", industry: "공기업", mark: "DJET", color: "#0054A6", bg: "#FFFFFF", aliases: ["대전도시철도공사", "djet"] },
  { name: "대전관광공사", industry: "공기업", mark: "대전관광공사", color: "#0054A6", bg: "#FFFFFF", aliases: ["대전마케팅공사"] },
  { name: "계룡건설", industry: "건설", mark: "KYERYONG", color: "#00529B", bg: "#FFFFFF", aliases: ["kyeryong", "계룡"] },
  { name: "골프존", industry: "플랫폼", mark: "GOLFZON", color: "#00A0E9", bg: "#FFFFFF", aliases: ["golfzon"] },
  { name: "레인보우로보틱스", industry: "자동차·중공업", mark: "Rainbow Robotics", color: "#333D4B", bg: "#FFFFFF", aliases: ["rainbowrobotics", "레인보우"] },
  { name: "알테오젠", industry: "제약·바이오", mark: "ALTEOGEN", color: "#333D4B", bg: "#FFFFFF", aliases: ["alteogen"] },
  { name: "레이언스", industry: "전자·IT", mark: "Rayence", color: "#333D4B", bg: "#FFFFFF", aliases: ["rayence"] },
  { name: "성심당", industry: "유통·식품", mark: "성심당", color: "#8B5A2B", bg: "#FFFFFF", aliases: ["sungsimdang", "로쏘"] },
  { name: "충남대학교병원", industry: "의료", mark: "충남대병원", color: "#0054A6", bg: "#FFFFFF", aliases: ["충남대병원", "cnuh"] },
  { name: "대전을지대학교병원", industry: "의료", mark: "을지대병원", color: "#0054A6", bg: "#FFFFFF", aliases: ["을지대병원", "을지병원"] },
  { name: "건양대학교병원", industry: "의료", mark: "건양대병원", color: "#0054A6", bg: "#FFFFFF", aliases: ["건양대병원"] },
  { name: "대전성모병원", industry: "의료", mark: "대전성모병원", color: "#0054A6", bg: "#FFFFFF", aliases: ["성모병원"] },
  { name: "대전선병원", industry: "의료", mark: "선병원", color: "#0054A6", bg: "#FFFFFF", aliases: ["선병원"] },
];

// 공백 제거 + 소문자 정규화
function normalize(str) {
  return String(str || "").toLowerCase().replace(/\s+/g, "");
}

/**
 * 회사 검색 (자동완성용)
 * - name / mark / aliases에 대해 공백 제거·소문자 부분일치
 * - 우선순위: 이름 시작 일치 > mark·alias 시작 일치 > 부분 일치
 * @param {string} query 검색어
 * @param {number} limit 최대 반환 개수 (기본 8)
 * @returns {Array} 매칭된 회사 객체 배열
 */
export function searchCompanies(query, limit = 8) {
  const q = normalize(query);
  if (!q) return [];

  const nameStarts = [];
  const otherStarts = [];
  const partials = [];

  for (const company of COMPANIES) {
    const name = normalize(company.name);
    const mark = normalize(company.mark);
    const aliases = company.aliases.map(normalize);

    if (name.startsWith(q)) {
      nameStarts.push(company);
    } else if (mark.startsWith(q) || aliases.some((a) => a.startsWith(q))) {
      otherStarts.push(company);
    } else if (
      name.includes(q) ||
      mark.includes(q) ||
      aliases.some((a) => a.includes(q))
    ) {
      partials.push(company);
    }
  }

  return [...nameStarts, ...otherStarts, ...partials].slice(0, limit);
}
